// https://www.rijksmuseum.nl
export const artworks = [
  {
    id: "en-SK-A-1718",
    priref: "5853",
    objectNumber: "SK-A-1718",
    language: "en",
    title: "Winter Landscape with Ice Skaters",
    copyrightHolder: null,
    webImage: {
      guid: "1332eb29-16f1-4e90-b60e-7786b7c24166",
      offsetPercentageX: 50,
      offsetPercentageY: 50,
      width: 2928,
      height: 1691,
      url:
        "https://lh3.googleusercontent.com/LW9vbQVQVGCgWznrQnEXKli4lRYmVFiUdEygCni9jDN2zXhXH4IpsgSD2aROfNoItYBCCzBv08REKrwQdUj3GqO3vdqj=s0",
    },
    colors: [
      "#B0AD92",
      " #64614A",
      " #D7D3BA",
      " #76806F",
      " #373B30",
      " #1F1C15",
      " #9E824E",
    ],
    colorsWithNormalization: [
      {
        originalHex: "#B0AD92",
        normalizedHex: "#E0CC91",
      },
      {
        originalHex: " #64614A",
        normalizedHex: "#737C84",
      },
      {
        originalHex: " #D7D3BA",
        normalizedHex: "#FBF6E1",
      },
      {
        originalHex: " #76806F",
        normalizedHex: "#737C84",
      },
      {
        originalHex: " #373B30",
        normalizedHex: "#2F4F4F",
      },
      {
        originalHex: " #1F1C15",
        normalizedHex: "#000000",
      },
      {
        originalHex: " #9E824E",
        normalizedHex: "#E0CC91",
      },
    ],
    normalizedColors: [
      "#D2B48C",
      " #696969",
      " #F5F5DC",
      " #808080",
      " #2F4F4F",
      " #000000",
      " #B8860B",
    ],
    normalized32Colors: [
      "#E0CC91",
      " #737C84",
      " #FBF6E1",
      " #2F4F4F",
      " #000000",
    ],
    titles: [
      "Winter Landscape with Skaters",
      "Winter Landscape with Iceskaters",
    ],
    description:
      "Winterlandschap met ijsvermaak. Dorpsgezicht met vele figuren op het ijs: schaatsers, kolfspelers, wandelaars. Rechts een arrenslede, links een kerk.",
    labelText: null,
    objectTypes: ["painting"],
    objectCollection: ["paintings"],
    makers: [],
    principalMakers: [
      {
        name: "Hendrick Avercamp",
        unFixedName: null,
        placeOfBirth: "Amsterdam",
        dateOfBirth: "1585",
        dateOfBirthPrecision: null,
        dateOfDeath: "1634",
        dateOfDeathPrecision: null,
        placeOfDeath: "Kampen",
        occupation: ["draughtsman"],
        roles: ["painter"],
        nationality: null,
        biography: null,
        productionPlaces: [],
        qualification: null,
      },
    ],
    plaqueDescriptionDutch:
      "Hendrick Avercamp maakte van het winterlandschap een zelfstandig onderwerp. Typerend voor zijn vroege landschappen is de hoge horizon. Deze stelde Avercamp in staat veel aandacht te besteden aan de tientallen figuurtjes op het ijs. Vanuit een vogelvluchtperspectief gaf hij veel amusante details weer, zoals het vrijende paartje en de poepende figuren links en de plassende man middenachter.",
    plaqueDescriptionEnglish:
      "\r\nHendrick Avercamp turned the winter landscape into a subject in its own right. A typical feature of his early work is the high horizon. This enabled Avercamp to focus on the dozens of figures on the ice. He showed all kinds of uncouth details in this bird’s-eye view, including couples making love and going to the toilet and in the distance, in the middle, a man urinating. ",
    principalMaker: "Hendrick Avercamp",
    artistRole: null,
    associations: [],
    acquisition: {
      method: "purchase",
      date: "1898-01-01T00:00:00Z",
      creditLine: "Purchased with the support of the Vereniging Rembrandt",
    },
    exhibitions: [],
    materials: ["panel", "oil paint (paint)"],
    techniques: [],
    productionPlaces: [],
    dating: {
      presentingDate: "c. 1608",
      sortingDate: 1608,
      period: 17,
      yearEarly: 1608,
      yearLate: 1608,
    },
    classification: {
      iconClassIdentifier: [
        "23F41",
        "43C244",
        "43C241",
        "43C41431",
        "11Q712",
        "47I1461",
      ],
      iconClassDescription: [
        "winter landscape; landscape symbolizing winter (the four seasons of the year)",
        "skates (winter sports)",
        "sledge, sleigh (winter sports)",
        "'kolf' on the ice",
        "church (exterior)",
        "hay-stack",
      ],
      motifs: [],
      events: [],
      periods: [],
      places: [],
      people: [],
      objectNumbers: ["SK-A-1718"],
    },
    hasImage: true,
    historicalPersons: [],
    inscriptions: [],
    documentation: [
      "Inzoomer object op zaal, 2013 (Nederlands/English).",
      "M. Verhoef, 'Van sneeuw naar verf', Kunstschrift 53 (2010) nr. 6, p. 14, 15",
      "Corine Koole, 'Literair levensverhaal : Hendrick Avercamp', Oog 3 (2009) nr. 5, p. 76-87.",
      "Marco van Baalen, 'Uitgelijnd : Winterlandschap met ijsvermaak', De Rijksmuseum Kunstkrant 30 (2005) nr. 1, p. 8-9.",
    ],
    catRefRPK: [],
    principalOrFirstMaker: "Hendrick Avercamp",
    dimensions: [
      {
        unit: "cm",
        type: "height",
        part: "support",
        value: "77.3",
      },
      {
        unit: "cm",
        type: "width",
        part: "support",
        value: "131.9",
      },
    ],
    physicalProperties: [],
    physicalMedium: "oil on panel",
    longTitle: "Winter Landscape with Ice Skaters, Hendrick Avercamp, c. 1608",
    subTitle: "h 77.3cm × w 131.9cm",
    scLabelLine: "Hendrick Avercamp (1585–1634), oil on panel, c. 1608",
    label: {
      title: "Winter Landscape with Ice Skaters",
      makerLine: "Hendrick Avercamp (1585–1634), oil on panel, c. 1608",
      description:
        "The high vantage point of this painting turns it into a sampler of human – and animal – activity during a harsh winter. Hundreds of people are out on the ice, most of them for pleasure, others working out of dire necessity. Avercamp did not shy away from grim details: in the left foreground crows and a dog feast on the carcass of a horse that has frozen to death.",
      notes: "Multimediatour",
      date: "2018-02-27",
    },
    showImage: true,
    location: "HG-2.6",
  },
  {
    id: "en-SK-C-6",
    priref: "5217",
    objectNumber: "SK-C-6",
    language: "en",
    title:
      "The Sampling Officials of the Amsterdam Drapers’ Guild, Known as ‘The Syndics’",
    copyrightHolder: null,
    webImage: {
      guid: "2c1ac367-9b11-4266-bb08-eea14ca0bb76",
      offsetPercentageX: 50,
      offsetPercentageY: 50,
      width: 3000,
      height: 1975,
      url:
        "https://lh3.googleusercontent.com/gShVRyvLLbwVB8jeIPghCXgr96wxTHaM4zqfmxIWRsUpMhMn38PwuUU13o1mXQzLMt5HFqX761u8Tgo4L_JG1XLATvw=s0",
    },
    colors: [
      "#8B7759",
      " #432F1C",
      " #16130C",
      " #B2A387",
      " #D5D0BA",
      " #745133",
    ],
    colorsWithNormalization: [
      {
        originalHex: "#8B7759",
        normalizedHex: "#E0CC91",
      },
      {
        originalHex: " #432F1C",
        normalizedHex: "#000000",
      },
      {
        originalHex: " #16130C",
        normalizedHex: "#000000",
      },
      {
        originalHex: " #B2A387",
        normalizedHex: "#E0CC91",
      },
      {
        originalHex: " #D5D0BA",
        normalizedHex: "#FBF6E1",
      },
      {
        originalHex: " #745133",
        normalizedHex: "#B35A1F",
      },
    ],
    normalizedColors: ["#000000", " #8B4513", " #D2B48C", " #F5F5DC"],
    normalized32Colors: ["#000000", " #B35A1F", " #E0CC91", " #FBF6E1"],
    titles: [
      "The Sampling Officials of the Amsterdam Drapers’ Guild, known as ‘The Syndics’",
      "The syndics: the sampling officials (wardens) of the Amsterdam drapers",
    ],
    description:
      "De Staalmeesters: het college van staalmeesters (waardijns) van het Amsterdamse lakenbereidersgilde, bijeen rond een tafel waarop een Perzisch kleed ligt, op tafel het opengeslagen stalenboek. Voorgesteld zijn (van links naar rechts): Jacob van Loon (1595-1674), Volckert Jansz (1605/10-81), Willem van Doeyenburg (ca. 1616-87), de knecht Frans Hendricksz Bel (1629-1701), Aernout van der Mye (ca. 1625-81) en Jochem de Neve (1629-81). Rechts boven de haard een schilderij met een brandend baken.",
    labelText: null,
    objectTypes: ["painting"],
    objectCollection: ["paintings"],
    makers: [],
    principalMakers: [
      {
        name: "Rembrandt van Rijn",
        unFixedName: null,
        placeOfBirth: "Leiden",
        dateOfBirth: "1606-07-15",
        dateOfBirthPrecision: null,
        dateOfDeath: "1669-10-08",
        dateOfDeathPrecision: null,
        placeOfDeath: "Amsterdam",
        occupation: ["print maker", "draughtsman", "painter"],
        roles: ["painter"],
        nationality: "Noord-Nederlands",
        biography: null,
        productionPlaces: [],
        qualification: null,
      },
    ],
    plaqueDescriptionDutch:
      "Staalmeesters controleerden de kwaliteit van geverfd laken. Rembrandt portretteerde hen in actie, alsof zij opkijken van hun werk. Eén meester staat op of gaat net zitten, waardoor niet alle hoofden zich op één lijn bevinden. Deze slimme ingreep, de vlotte penseelstreken en de subtiele lichtval maken dit werk tot een van de levendigste groepsportretten uit de 17de eeuw. Het doek werd geschilderd voor de Staalhof, maar verhuisde in 1771 naar het Amsterdamse stadhuis.",
    plaqueDescriptionEnglish:
      "Samplers checked the quality of dyed cloth. Here Rembrandt shows them at work, distracted for a moment and looking up. One syndic is about to sit, or stand, so not all the heads are at the same level. A clever trick which, with the confident brushwork and subtle use of light, make this one of the liveliest group portraits of the 17th century. Originally painted for the sampling hall (Staalhof), in 1771 it was acquired by Amsterdam’s town hall.",
    principalMaker: "Rembrandt van Rijn",
    artistRole: null,
    associations: [],
    acquisition: {
      method: "loan",
      date: "1808-01-01T00:00:00Z",
      creditLine: "On loan from the City of Amsterdam",
    },
    exhibitions: [],
    materials: ["canvas", "oil paint (paint)"],
    techniques: [],
    productionPlaces: [],
    dating: {
      presentingDate: "1662",
      sortingDate: 1662,
      period: 17,
      yearEarly: 1662,
      yearLate: 1662,
    },
    classification: {
      iconClassIdentifier: ["47E241", "41A711", "49MM32"],
      iconClassDescription: [
        "officers trusted with control of quality",
        "table",
        "book - MM - book open",
      ],
      motifs: [],
      events: [],
      periods: [],
      places: ["Amsterdam"],
      people: [
        "Loon, Jacob van",
        "Jansz, Volckert",
        "Doeyenburg, Willem van",
        "Bel, Frans Hendricksz",
        "Mye, Aernout van der",
        "Neve, Jochem de",
      ],
      objectNumbers: ["SK-C-6"],
    },
    hasImage: true,
    historicalPersons: [
      "Loon, Jacob van",
      "Jansz, Volckert",
      "Doeyenburg, Willem van",
      "Bel, Frans Hendricksz",
      "Mye, Aernout van der",
      "Neve, Jochem de",
    ],
    inscriptions: [],
    documentation: [
      "Tim Zeedijk, ‘Why Carpets are Beautiful’, in Kneeling, 5 years of Making Carpets, Eindhoven (MU Artspace) 2014, afb. p. 10.",
      "N. Middelkoop, 'Kruisbestuiving : Schutters- en regentenstukken in Haarlem en Amsterdam', Kunstschrift (2014) nr. 4, p. 34, afb. 34-35.",
      "The Rembrandt Database,  Object information, Rembrandt,  The sampling officials of the Amsterdam drapers guild,  dated 1662, Rijksmuseum, Amsterdam, inv. no. SK-C-6, http://www.rembrandtdatabase.org/Rembrandt/painting/3046/the-sampling-officials-of-the-amsterdam-drapers-guild, accessed 2016 February 01",
      "B. Alsdorf, La fraternité des individus: les portraits de groupe de Degas, in: La revue de Musée d'Orsay nr. 30 (automne 2010) 48, 14, p. 25, fig. 9",
      "R. Bergmans, Rembrandts kijk op De Staalmeesters, 2009-07- http://mathart.come2me.nl/1014134/REMBRANDT-Staalmeesters [artikel over het perspectief]",
      "Marleen Dominicus-Van Soest, 'Rembrandt in nieuw licht', Rijksmuseum Kunstkrant 19 (1993) nr. 3.",
      "J.G. van Gelder, 'De Staalmeesters', Openbaar Kunstbezit (1964), p. 11a/b.",
      'I.H. van Eeghen, "De Staalmeesters", Jaarboek Amstelodamum 1956, p. 65 - 80',
      "Inzoomer object op zaal, 2013 (Nederlands/English).",
    ],
    catRefRPK: [],
    principalOrFirstMaker: "Rembrandt van Rijn",
    dimensions: [
      {
        unit: "cm",
        type: "height",
        part: null,
        value: "191.5",
      },
      {
        unit: "cm",
        type: "width",
        part: null,
        value: "279",
      },
    ],
    physicalProperties: [],
    physicalMedium: "oil on canvas",
    longTitle:
      "The Sampling Officials of the Amsterdam Drapers’ Guild, Known as ‘The Syndics’, Rembrandt van Rijn, 1662",
    subTitle: "h 191.5cm × w 279cm",
    scLabelLine: "oil on canvas, 1662",
    label: {
      title:
        "The Sampling Officials of the Amsterdam Drapers’ Guild, Known as ‘The Syndics’",
      makerLine: "oil on canvas, 1662",
      description:
        "After suffering financial difficulties in the 1650s, Rembrandt moved to a rental house on the Rozengracht. The Amsterdam élite no longer knocked on his door as often as they had done before. He nevertheless remained popular: this important guild commissioned him to paint a group portrait. Rembrandt produced a lively scene by having the wardens look up from their work as if interrupted by our arrival.",
      notes: "Multimediatour Alle Rembrandts,  2118",
      date: "2019-02-26",
    },
    showImage: true,
    location: "PV-1.4",
  },

  {
    id: "en-SK-C-5",
    priref: "5216",
    objectNumber: "SK-C-5",
    language: "en",
    title:
      "Militia Company of District II under the Command of Captain Frans Banninck Cocq, Known as the ‘Night Watch’",
    copyrightHolder: null,
    webImage: {
      guid: "aa08df9c-0af9-4195-b31b-f578fbe0a4c9",
      offsetPercentageX: 50,
      offsetPercentageY: 100,
      width: 2500,
      height: 2034,
      url:
        "https://lh3.googleusercontent.com/J-mxAE7CPu-DXIOx4QKBtb0GC4ud37da1QK7CzbTIDswmvZHXhLm4Tv2-1H3iBXJWAW_bHm7dMl3j5wv_XiWAg55VOM=s0",
    },
    colors: [
      "#261808",
      " #5E3C14",
      " #9C8238",
      " #885617",
      " #AF9F6B",
      " #6C6238",
      " #D7CB9E",
    ],
    colorsWithNormalization: [
      {
        originalHex: "#261808",
        normalizedHex: "#000000",
      },
      {
        originalHex: " #5E3C14",
        normalizedHex: "#B35A1F",
      },
      {
        originalHex: " #9C8238",
        normalizedHex: "#E09714",
      },
      {
        originalHex: " #885617",
        normalizedHex: "#B35A1F",
      },
      {
        originalHex: " #AF9F6B",
        normalizedHex: "#E0CC91",
      },
      {
        originalHex: " #6C6238",
        normalizedHex: "#367614",
      },
      {
        originalHex: " #D7CB9E",
        normalizedHex: "#E0CC91",
      },
    ],
    normalizedColors: [
      "#000000",
      " #8B4513",
      " #B8860B",
      " #BDB76B",
      " #556B2F",
      " #F5DEB3",
    ],
    normalized32Colors: [
      "#000000",
      " #B35A1F",
      " #E09714",
      " #E0CC91",
      " #367614",
    ],
    titles: [
      "Officers and other civic guardsmen of District II in Amsterdam, under the command of Captain Frans Banninck Cocq and Lieutenant Willem van Ruytenburch, known as ‘The Night Watch’",
      "The company of Captain Frans Banninck Cocq and Lieutenant Willem van Ruytenburch, known as 'The nightwatch'",
    ],
    description:
      "Het korporaalschap van kapitein Frans Banninck Cocq en luitenant Willem van Ruytenburch, bekend als de 'Nachtwacht'. Schutters van de kloveniersdoelen uit een poort naar buiten tredend. Op een schild aangebracht naast de poort staan de namen van de afgebeelde personen: Frans Banning Cocq, heer van purmerlant en Ilpendam, Capiteijn Willem van Ruijtenburch van Vlaerdingen, heer van Vlaerdingen, Lu[ij]tenant, Jan Visscher Cornelisen Vaendrich, Rombout Kemp Sergeant, Reijnier Engelen Sergeant, Barent Harmansen, Jan Adriaensen Keyser, Elbert Willemsen, Jan Clasen Leydeckers, Jan Ockersen, Jan Pietersen bronchorst, Harman Iacobsen wormskerck, Jacob Dircksen de Roy, Jan vander heede, Walich Schellingwou, Jan brugman, Claes van Cruysbergen, Paulus Schoonhoven. De schutters zijn gewapend met lansen, musketten en hellebaarden. Rechts de tamboer met een grote trommel. Tussen de soldaten links staat een meisje met een dode kip om haar middel, rechts een blaffende hond. Linksboven de vaandrig met de uitgestoken vaandel.",
    labelText: null,
    objectTypes: ["painting"],
    objectCollection: ["paintings"],
    makers: [],
    principalMakers: [
      {
        name: "Rembrandt van Rijn",
        unFixedName: null,
        placeOfBirth: "Leiden",
        dateOfBirth: "1606-07-15",
        dateOfBirthPrecision: null,
        dateOfDeath: "1669-10-08",
        dateOfDeathPrecision: null,
        placeOfDeath: "Amsterdam",
        occupation: ["print maker", "draughtsman", "painter"],
        roles: ["painter"],
        nationality: "Noord-Nederlands",
        biography: null,
        productionPlaces: ["Amsterdam"],
        qualification: null,
      },
    ],
    plaqueDescriptionDutch:
      "Rembrandts beroemdste en grootste doek werd gemaakt voor de Kloveniersdoelen. Dit was een van de verenigingsgebouwen van de Amsterdamse schutterij, de burgerwacht van de stad. \r\nRembrandt was de eerste die op een groepsportret de figuren in actie weergaf. De kapitein, in het zwart, geeft zijn luitenant opdracht dat de compagnie moet gaan marcheren. De schutters stellen zich op. Met behulp van licht vestigde Rembrandt de aandacht op belangrijke details, zoals het handgebaar van de kapitein en het kleine meisje op de achtergrond. Zij is de mascotte van de schutters.",
    plaqueDescriptionEnglish:
      "Rembrandt’s largest, most famous canvas was made for the Arquebusiers guild hall. This was one of several halls of Amsterdam’s civic guard, the city’s militia and police. \r\nRembrandt was the first to paint figures in a group portrait actually doing something. The captain, dressed in black, is telling his lieutenant to start the company marching. The guardsmen are getting into formation. Rembrandt used the light to focus on particular details, like the captain’s gesturing hand and the young girl in the foreground. She was the company mascot.\r\n",
    principalMaker: "Rembrandt van Rijn",
    artistRole: null,
    associations: [],
    acquisition: {
      method: "loan",
      date: "1808-01-01T00:00:00Z",
      creditLine: "On loan from the City of Amsterdam",
    },
    exhibitions: [],
    materials: ["canvas", "oil paint (paint)"],
    techniques: [],
    productionPlaces: ["Amsterdam"],
    dating: {
      presentingDate: "1642",
      sortingDate: 1642,
      period: 17,
      yearEarly: 1642,
      yearLate: 1642,
    },
    classification: {
      iconClassIdentifier: [
        "45(+26)",
        "45C1",
        "48C7341",
        "31D11222",
        "45D12",
        "34B11",
      ],
      iconClassDescription: [
        "warfare; military affairs (+ citizen soldiery, civil guard, citizen militia)",
        "weapons",
        "drum (musical instrument)",
        "girl (child between toddler and youth)",
        "(military) standard-bearer",
        "dog",
      ],
      motifs: [],
      events: [],
      periods: [],
      places: ["Amsterdam"],
      people: [
        "Banninck Cocq, Frans",
        "Ruytenburch, Willem van",
        "Visscher Cornelisen, Jan",
        "Kemp, Rombout",
        "Engelen, Reijnier Janszn",
        "Bolhamer, Barent Harmansen",
        "Keijser, Jan Adriaensen",
        "Willemsen, Elbert",
        "Leijdeckers, Jan Claesen",
        "Ockersen, Jan",
        "Bronchorst, Jan Pietersen",
        "Wormskerck, Harman Jacobsen",
        "Roy, Jacob Dircksen de",
        "Heede, Jan van der",
      ],
      objectNumbers: ["SK-C-5"],
    },
    hasImage: true,
    historicalPersons: [
      "Banninck Cocq, Frans",
      "Ruytenburch, Willem van",
      "Visscher Cornelisen, Jan",
      "Kemp, Rombout",
      "Engelen, Reijnier Janszn",
      "Bolhamer, Barent Harmansen",
      "Keijser, Jan Adriaensen",
      "Willemsen, Elbert",
      "Leijdeckers, Jan Claesen",
      "Ockersen, Jan",
      "Bronchorst, Jan Pietersen",
      "Wormskerck, Harman Jacobsen",
      "Roy, Jacob Dircksen de",
      "Heede, Jan van der",
    ],
    inscriptions: [],
    documentation: [
      "The Rembrandt Database,  Object information, Rembrandt,  Civic guardsmen of Amsterdam under command of Banninck Cocq,  dated 1642, Rijksmuseum, Amsterdam, inv. no. SK-C-5, http://www.rembrandtdatabase.org/Rembrandt/painting/3063/civic-guardsmen-of-amsterdam-under-command-of-banninck-cocq, accessed 2016 February 01",
      "Inzoomer object op zaal, 2013 (Nederlands/English).",
      "A. Jensen Adams, Public Faces and Private Identities in Seventeenth-Century Holland, Portraiture and the Production of Community, New York 2009, p. 211-217, fig. 60.",
      "M. Rayssac, 'l'Exode des Musées, Histoire des oeuvres d'art sous l'Occupation', Parijs 2007.",
      "K.M. Groen, 'Earth Matters, The origin of the material used for the preparation of the Nightwatch and many other canvases in Rembrandt's workshop after 1640', Art Matters, volume 3, p. 138.",
      "E. Runia. A. van Suchtelen, Rembrandt, Den Haag 2006, p. 14.",
      "Y. van Veelen, 'Work in progress. De strijd om de Nachtwacht', Kunstbeeld nr. 12/1 (dec. 2004/jan. 2005), p. 44-47.",
      "'Omtrents Rembrandts Nachtwacht', Kunstkrant Rijksmuseum Amsterdam nr. 1 (1998), p. 14-20.",
      "H. van Os, in: Bulletin van het Rijksmuseum nr. 4 (1996), p. 309-320 + afb.",
      "J. Boomgaard, 'De Verloren Zoon. Rembrandt en de Nederlandse Kunstgeschiedenisbeschrijving', Kunstreeks (1995).",
      "P. Taylor, 'Darkness at Noon. Rembrandts Nachtwacht', Kunstschrift 6 (1994), p. 22-27 + afb.",
      "Fieke Tissink, 'Hoofdstuk uit het Rijksmuseum', Rijksmuseum Kunstkrant 19 (1993) nr. 3, p. 14-18.",
      "O. Pacht, 'Rembrandt', Munchen 1991, p. 19-30 + ill.",
      "A.K. Wheelock, 'The Age of Rembrandt', Studies in seventeenth Century Dutch Painting (The Pennsylvania State University, 1988), p. 215, 223 (afb.).",
      "J.B. Bedaux, 'Een achttiende eeuwse kunsttheoretische discussie', Kunstlicht 15 (1985), p. 25-28.",
      "C. Grimm, 'Handschrift, schildertechniek en beeldstructuur. Bijdrage tot het onderzoek naar toeschrijving, I: de helmen van Rembrandt', Tableau (1982/83), p. 246-248, afb. 5.",
      "E. van de Wetering, 'Ontrouw aan Rembrandt', Kunstschrift (Openbaar Kunstbezit) (1982), p. 166-167, 171, afb. 24-26.",
      "K. Clark, 'What is a masterpiece?', Portfolio. The Magazine of the Visual Arts, 2 (1980), p. 51 + afb.",
      "H. Günther, 'Damals oder heute unverstanden. Zum Problem von Rembrandts Nachtwache', Welkunst 50 (1980), p. 1848-1850 + afb.",
      "U. Schumacher, 'Gruppenporträt und Genrebild. Zur Deutung der Photographie fur die franzosische Malerei des 19. Jahrhunderts, Giessener Beiträge zur Kunstgeschichte 4 (1979), p. 29, afb. 11.",
      "M.M. Toth-Ubbens, 'De barbier van Amsterdam. Aantekeningen over de relaties tussen het Waaggebouw en de Schouwburg in de zeventiende eeuw', Antiek 10 (1975), p. 388, afb. 12.",
      "H. Gerson, 'De Nachtwacht', Openbaar Kunstbezit, 10e jaargang, januari (1966).",
      "Chr. White, 'Rembrandt', Den Haag 1964, p. 65, 66 + afb.",
      "A.J. Moes-Veth, 'Rembrandt's Claudius Civilis en de Nachtwacht van terzijde beschouwd, Oud Holland LXXV (1960), p. 143.",
      "A.J. Moes-Veth, 'De Nachtwacht en haar oude copieen', Oud Holland LXII (1947), p. 188.",
      "J.A. Overhoff, 'De Nachtwacht op zwerftocht' (het schilderij ten tijde van WO II), http://www.cacciucco.nl/artikelen/kunst/de_nachtwacht_op_zwerftocht.html [2016]",
      "J.A. Overhoff, 'THE NIGHT WATCH ODYSSEY' (the painting during WWII) , http://www.cacciucco.nl/english/the_night_watch_odyssey.html [2017]",
    ],
    catRefRPK: [],
    principalOrFirstMaker: "Rembrandt van Rijn",
    dimensions: [
      {
        unit: "cm",
        type: "height",
        part: null,
        value: "379.5",
      },
      {
        unit: "cm",
        type: "width",
        part: null,
        value: "453.5",
      },
      {
        unit: "kg",
        type: "weight",
        part: null,
        value: "337",
      },
      {
        unit: "kg",
        type: "weight",
        part: null,
        value: "170",
      },
    ],
    physicalProperties: [],
    physicalMedium: "oil on canvas",
    longTitle:
      "Militia Company of District II under the Command of Captain Frans Banninck Cocq, Known as the ‘Night Watch’, Rembrandt van Rijn, 1642",
    subTitle: "h 379.5cm × w 453.5cm × w 337kg",
    scLabelLine: "Rembrandt van Rijn (1606–1669), oil on canvas, 1642",
    label: {
      title:
        "Militia Company of District II under the Command of Captain Frans Banninck Cocq, Known as the ‘Night Watch’",
      makerLine: "Rembrandt van Rijn (1606–1669), oil on canvas, 1642",
      description: null,
      notes: "Multimediatour",
      date: "2018-02-27",
    },
    showImage: true,
    location: "HG-2.31",
  },

  {
    id: "en-SK-A-2344",
    priref: "6417",
    objectNumber: "SK-A-2344",
    language: "en",
    title: "The Milkmaid",
    copyrightHolder: null,
    webImage: {
      guid: "e4e3005c-dd9e-4db6-b466-50b17a9a52cd",
      offsetPercentageX: 50,
      offsetPercentageY: 27,
      width: 2261,
      height: 2548,
      url:
        "https://lh3.googleusercontent.com/cRtF3WdYfRQEraAcQz8dWDJOq3XsRX-h244rOw6zwkHtxy7NHjJOany7u4I2EG_uMAfNwBLHkFyLMENzpmfBTSYXIH_F=s0",
    },
    colors: [
      "#7E6E50",
      " #E3E0CB",
      " #B7AD89",
      " #3C4C76",
      " #7587A4",
      " #201D20",
    ],
    colorsWithNormalization: [
      {
        originalHex: "#7E6E50",
        normalizedHex: "#E0CC91",
      },
      {
        originalHex: " #E3E0CB",
        normalizedHex: "#FBF6E1",
      },
      {
        originalHex: " #B7AD89",
        normalizedHex: "#E0CC91",
      },
      {
        originalHex: " #3C4C76",
        normalizedHex: "#4279DB",
      },
      {
        originalHex: " #7587A4",
        normalizedHex: "#737C84",
      },
      {
        originalHex: " #201D20",
        normalizedHex: "#000000",
      },
    ],
    normalizedColors: [
      "#000000",
      " #D2B48C",
      " #696969",
      " #483D8B",
      " #778899",
      " #F5F5DC",
    ],
    normalized32Colors: [
      "#000000",
      " #E0CC91",
      " #4279DB",
      " #737C84",
      " #FBF6E1",
    ],
    titles: ["The Milkmaid"],
    description:
      "Een dienstmaagd staat achter een tafel en schenkt melk uit een melkkan in een kookpot. Op de tafel staat een mand met brood en een stenen kruik, links een venster met een rieten mand en een koperen pot. Onderaan de muur rechts een rijtje tegels en een stoofje.",
    labelText: null,
    objectTypes: ["painting"],
    objectCollection: ["paintings"],
    makers: [],
    principalMakers: [
      {
        name: "Johannes Vermeer",
        unFixedName: null,
        placeOfBirth: "Delft",
        dateOfBirth: "1632-10-31",
        dateOfBirthPrecision: null,
        dateOfDeath: "1675-12-15",
        dateOfDeathPrecision: null,
        placeOfDeath: "Delft",
        occupation: ["draughtsman", "painter"],
        roles: ["painter"],
        nationality: "Noord-Nederlands",
        biography: null,
        productionPlaces: [],
        qualification: null,
      },
    ],
    plaqueDescriptionDutch:
      "Geconcentreerd schenkt een keukenmeid melk uit een kan. De voorstelling is heel verstild. Alleen het straaltje melk lijkt te bewegen. Van een alledaags onderwerp en een eenvoudige compositie wist Vermeer een indringend schilderij te maken.\r\nVooral in de weergave van het licht onderscheidt Vermeer zich. Met kleine puntjes geeft hij de glimlichtjes weer, zoals bijvoorbeeld op het brood en het blauwe kleed. ",
    plaqueDescriptionEnglish:
      "A maid concentrates keenly as she pours milk from a jug. It is a quiet, tranquil scene. The only movement is the flow of milk. Vermeer turned a simple composition of a prosaic subject into an intense work of art.\r\nIt is in the rendering of light that Vermeer truly excelled, painting tiny dots for highlights, as on the bread and the blue cloth.",
    principalMaker: "Johannes Vermeer",
    artistRole: null,
    associations: [],
    acquisition: {
      method: "purchase",
      date: "1908-01-01T00:00:00Z",
      creditLine: "Purchased with the support of the Vereniging Rembrandt",
    },
    exhibitions: [],
    materials: ["canvas", "oil paint (paint)"],
    techniques: [],
    productionPlaces: [],
    dating: {
      presentingDate: "c. 1660",
      sortingDate: 1660,
      period: 17,
      yearEarly: 1660,
      yearLate: 1660,
    },
    classification: {
      iconClassIdentifier: [
        "41C222",
        "47I22311",
        "41C6413",
        "41C621",
        "41B23",
        "41A773",
      ],
      iconClassDescription: [
        "kitchen-maid, kitchen servant",
        "milkmaid",
        "milk",
        "bread, loaf",
        "foot-stove",
        "container of ceramics: jar, jug, pot, vase",
      ],
      motifs: [],
      events: [],
      periods: [],
      places: [],
      people: [],
      objectNumbers: ["SK-A-2344"],
    },
    hasImage: true,
    historicalPersons: [],
    inscriptions: [],
    documentation: [
      "Gijsbert van der Wal, 'Schilderen in druppeltjes', Kunstschrift (2014) nr. 3, p. 13, afb. 11.",
      "P. Hecht, 'Daniël Franken : genereus en bescheiden', Bulletin van de Vereniging Rembrandt 24 (2014), afb. p. 10.",
      "Bikker, Jonathan, 'The hidden collection of the spectacularly bankrupt banker Leendert Pieter de Neufville', Simiolus 36 (2012), nr. 3/4, p. 196, afb. 21.",
      "The New York Times, 13 sept. 2009, p. 77 [paginagrote advertentie van The Metropolitan Museum of Art].",
      "Karen Rosenberg, 'A humble domestic crosses the sea/ocean', The New York Times, 11 sept. 2009, p. 23, 29.",
      "Pieter Roelofs, 'Nu of nooit : na 300 jaar weer samen', Oog 3 (2009) nr. 1, p. 80-81.",
      "Z.Z. Filipczak, 'Vermeer, elusiveness, and visual theory', Simiolus 32 (2006), nr. 4, p. 263, afb. 2.",
      "C. van der Bas, 'The Muilman Collection: the progressive taste of an eighteenth-century banking family', Simiolus 32, (2006), nr. 2/3, p. 156",
    ],
    catRefRPK: [],
    principalOrFirstMaker: "Johannes Vermeer",
    dimensions: [
      {
        unit: "cm",
        type: "height",
        part: null,
        value: "45.5",
      },
      {
        unit: "cm",
        type: "width",
        part: null,
        value: "41",
      },
    ],
    physicalProperties: [],
    physicalMedium: "oil on canvas",
    longTitle: "The Milkmaid, Johannes Vermeer, c. 1660",
    subTitle: "h 45.5cm × w 41cm",
    scLabelLine: "Johannes Vermeer (1632–1675), oil on canvas, c. 1660",
    label: {
      title: "The Milkmaid",
      makerLine: "Johannes Vermeer (1632–1675), oil on canvas, c. 1660",
      description:
        "A maidservant pours milk, entirely absorbed in her work. Except for the stream of milk, everything else is still. Vermeer took this simple everyday activity and made it the subject of an impressive painting – the woman stands like a statue in the brightly lit room. Vermeer also had an eye for how light by means of hundreds of colourful dots plays over the surface of objects.",
      notes: "Multimediatour",
      date: "2018-02-27",
    },
    showImage: true,
    location: "HG-2.30.3",
  },

  {
    id: "en-SK-C-2",
    priref: "8662",
    objectNumber: "SK-C-2",
    language: "en",
    title:
      "Banquet at the Crossbowmen’s Guild in Celebration of the Treaty of Münster",
    copyrightHolder: null,
    webImage: {
      guid: "68df1929-68ba-4d9a-becc-e60289f7a7ef",
      offsetPercentageX: 50,
      offsetPercentageY: 50,
      width: 2500,
      height: 1034,
      url:
        "https://lh3.googleusercontent.com/kmCDKP1kMN72zB-7CHBOBdCnyU3Z-NW7WIzuN_sIqm5n9xf6lG4oTtfcWsGW8qhbVYuwSDkYlhOglx7z4YaFL8UeFWU=s0",
    },
    colors: [
      "#120F09",
      " #4E402C",
      " #856E47",
      " #9F8E6A",
      " #ABA892",
      " #425763",
      " #C7C5B1",
    ],
    colorsWithNormalization: [
      {
        originalHex: "#120F09",
        normalizedHex: "#000000",
      },
      {
        originalHex: " #4E402C",
        normalizedHex: "#737C84",
      },
      {
        originalHex: " #856E47",
        normalizedHex: "#B35A1F",
      },
      {
        originalHex: " #9F8E6A",
        normalizedHex: "#E0CC91",
      },
      {
        originalHex: " #ABA892",
        normalizedHex: "#E0CC91",
      },
      {
        originalHex: " #425763",
        normalizedHex: "#2F4F4F",
      },
      {
        originalHex: " #C7C5B1",
        normalizedHex: "#FBF6E1",
      },
    ],
    normalizedColors: [
      "#000000",
      " #696969",
      " #D2B48C",
      " #A9A9A9",
      " #2F4F4F",
      " #C0C0C0",
    ],
    normalized32Colors: [
      "#000000",
      " #737C84",
      " #B35A1F",
      " #E0CC91",
      " #2F4F4F",
      " #FBF6E1",
    ],
    titles: [
      "The Celebration of the Peace of Münster, 18 June 1648, in the Headquarters of the Crossbowmen's Civic Guard (St George Guard), Amsterdam",
    ],
    description:
      "De schuttersmaaltijd in de Voetboogdoelen of St. Jorisdoelen te Amsterdam ter viering van het sluiten van de vrede van Munster, 18 juni 1648. Voorgesteld zijn: kapitein Cornelis Jansz Witsen (met de zilveren drinkhoorn), luitenant Johan Oetgens van Waveren (die zijn hand schudt), de vaandrig Jacob Banningh (zittend naast de grote trommel), Dirck Claesz Thoveling en Thomas Hartog (sergeanten), Pieter van Hoorn, Willem Pietersz van der Voort, Adriaen Dirck Sparwer, Hendrick Calaber, Govert van der Mij, Johannes Calaber, Benedictus Schaeck, Jan Maes, Jacob van Diemen, Jan van Ommeren, Isaac Ooyens, Gerrit Pietersz van Anstenraadt, Herman Teunisz de Kluyter, Andries van Anstenraadt, Christoffel Poock, Hendrick Dommer Wz, Paulus Hennekijn, Lambregt van den Bos en Willem (de trommelslager). Op de grote trommel hangt een papier met een gedicht van Jan Vos. Door de openstaande ramen is de gevel van de brouwerij 'het Lam' aan de Singel zichtbaar. Rechts brengt een vrouwen een kalkoenpastei binnen. Op tafel staan tinnen borden, roemers en andere glazen. Links staat op de vloer een grote metalen koeler met een wijnvat.",
    labelText: null,
    objectTypes: ["painting"],
    objectCollection: ["paintings"],
    makers: [],
    principalMakers: [
      {
        name: "Bartholomeus van der Helst",
        unFixedName: null,
        placeOfBirth: "Haarlem",
        dateOfBirth: "1613",
        dateOfBirthPrecision: null,
        dateOfDeath: "1670-12-16",
        dateOfDeathPrecision: null,
        placeOfDeath: "Amsterdam",
        occupation: ["draughtsman", "painter"],
        roles: ["painter"],
        nationality: "Noord-Nederlands",
        biography: null,
        productionPlaces: [],
        qualification: null,
      },
    ],
    plaqueDescriptionDutch:
      "Schutters vormden de gewapende macht van de stad. Zij waren vrijwilligers. In Amsterdam had elk stadsdeel een eigen schutterij met een eigen verenigingsgebouw. In de 17de eeuw werden die gebouwen groter en mooier. De interieurs werden versierd met groepsportretten van de leden. In 1648 legde Van der Helst Amsterdamse schutters vast in hun verenigingsgebouw, waar zij de vrede tussen Nederland en Spanje vierden.",
    plaqueDescriptionEnglish:
      "Civic guards were the city’s militia. They were volunteers. In Amsterdam, each district had its own company with its own headquarters. In the 17th century, larger and grander buildings were built. Group portraits of the members lined the walls. In 1648, Van der Helst immortalised this Amsterdam company in their hall, celebrating the peace between Spain and the Dutch Republic.",
    principalMaker: "Bartholomeus van der Helst",
    artistRole: null,
    associations: [],
    acquisition: {
      method: "loan",
      date: "1808-01-01T00:00:00Z",
      creditLine: "On loan from the City of Amsterdam",
    },
    exhibitions: [],
    materials: ["canvas", "oil paint (paint)"],
    techniques: [],
    productionPlaces: [],
    dating: {
      presentingDate: "1648",
      sortingDate: 1648,
      period: 17,
      yearEarly: 1648,
      yearLate: 1648,
    },
    classification: {
      iconClassIdentifier: ["41C5", "43A2", "45(+26)", "41C323", "45D1"],
      iconClassDescription: [
        "celebration meal, feast, banquet",
        "private festivities, merry company",
        "warfare; military affairs (+ citizen soldiery, civil guard, citizen militia)",
        "glass, rummer",
        "(military) flags and standards",
      ],
      motifs: [],
      events: [
        "Vrede van Münster",
        "Viering van de Vrede van Munster te Amsterdam",
      ],
      periods: ["1648-06-181648-06-18"],
      places: ["Amsterdam"],
      people: ["Witsen, Cornelis"],
      objectNumbers: ["SK-C-2"],
    },
    hasImage: true,
    historicalPersons: ["Witsen, Cornelis"],
    inscriptions: [],
    documentation: [
      "Nina Geerdink, 'Jan Vos (1610-1667), de schilderkunst en de Amsterdamse regenten', Oud Holland 127 (2014) nr. 2/3, p. 96, afb. 2.",
      "Inzoomer object op zaal, 2013 (Nederlands/English).",
      "Jaarverslag Rijksmuseum (2011), afb. p. 86, afb. p. 96.",
      "Judith van Gent, 'Een 'vleyend penceel' : Bertholomeus van der Helst : begaafd schilder van de Amsterdamse elite', Ons Amsterdam 63 (2011) nr. 10, p. 408-409.",
      "Rijksmuseum Kunstkrant 33 (2007) sept.-okt., nr. 5, p. 9",
      "Rijksmuseum Amsterdam Jaarverslag 2006, p. 53",
      "Annual report : Rijksmuseum Amsterdam (1999), p. 38-39, afb.",
      "P. Jeroense, 'Govert Flinck. Eine Künstlerbiographie', Niederdeutsche Beitrage zur Kunstgeschichte 36 (1997), p. 90.",
      "J. Bos, 'Capitaele Stucken', Jaarboek Amstelodamum 88 (1996), p. 65-102.",
      "R. Jellema, 'De Schuttersmaaltijd door Van der Helst in het Teylers Museum?', Teylers Museum Magazijn 16 (1987), p. 1-4.",
      "R.B.F. van der Sloot en J.B. Kist, 'Iets over de degenvesten in Hoorn rond het jaar 1650', Armamentaria 5 (1970), p. 16.",
      "A.-E. Theuerkauff-Liederwald, 'Die niederländischen Gläser aus dem Gemälde von Bathelomäus van der Helst 'Schütsenmahlzeit am 18. Juni 1648 in der St. Jorisdoelen zu Amsterdam'', Rijksmuseum Amsterdam, ICOM glass Congress, Brussel 1965, paper 266",
      "A.J de Bull, 'Van der Helst - Kaiser', Kunstkronijk (1856), p. 59-60.",
      "Documentatiemap: aantekeningen R. van Luttervelt.",
    ],
    catRefRPK: [],
    principalOrFirstMaker: "Bartholomeus van der Helst",
    dimensions: [
      {
        unit: "cm",
        type: "height",
        part: null,
        value: "232",
      },
      {
        unit: "cm",
        type: "width",
        part: null,
        value: "547",
      },
    ],
    physicalProperties: [],
    physicalMedium: "oil on canvas",
    longTitle:
      "Banquet at the Crossbowmen’s Guild in Celebration of the Treaty of Münster, Bartholomeus van der Helst, 1648",
    subTitle: "h 232cm × w 547cm",
    scLabelLine: "Bartholomeus van der Helst (1613–1670), oil on canvas, 1648",
    label: {
      title:
        "Banquet at the Crossbowmen’s Guild in Celebration of the Treaty of Münster",
      makerLine: "Bartholomeus van der Helst (1613–1670), oil on canvas, 1648",
      description:
        "18 June 1648: a banquet is taking place at the Amsterdam crossbowmen’s guild. The occasion was the signing of the Treaty of Münster, which marked an end to the war with Spain. The captains of the civic guard company shake hands as a sign of peace, and the drinking horn is passed around. The poem on the drum proclaims the joy of Amsterdam’s armed militia that their weapons can henceforth be laid to rest.",
      notes: "Multimediatour",
      date: "2018-02-27",
    },
    showImage: true,
    location: "HG-2.8",
  },
];
